// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddEssay: typeof import('./src/components/containner/items/addEssay.vue')['default']
    Card: typeof import('./src/components/commen/Card.vue')['default']
    Containner: typeof import('./src/components/containner/containner.vue')['default']
    Drawer: typeof import('./src/components/commen/Drawer.vue')['default']
    EditEssay: typeof import('./src/components/containner/items/editEssay.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EssayList: typeof import('./src/components/containner/items/essayList.vue')['default']
    EssayTable: typeof import('./src/components/containner/items/essayTable.vue')['default']
    Home: typeof import('./src/components/containner/items/home.vue')['default']
    Link: typeof import('./src/components/containner/items/Link.vue')['default']
    NavList: typeof import('./src/components/containner/items/NavList.vue')['default']
    PopBox: typeof import('./src/components/commen/popBox.vue')['default']
    PopUp: typeof import('./src/components/utils/pop-up.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Side: typeof import('./src/components/side/side.vue')['default']
    Slider: typeof import('./src/components/commen/slider.vue')['default']
  }

}
